### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by bramp** [dart-lang/setup-dart#121]
I get the following warning in my build summary

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dart-lang/setup-dart@v1.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

This looks a simple fix [action.yml](https://github.com/dart-lang/setup-dart/blob/main/action.yml) (changing `using: "node16"` to using: `"using: "node20"`), but I honestly I don't know how to test the new action, so I figured I'd leave it to the professionals :)

thanks

**Comment by devoncarew** [comment]
Thanks for the report! I see this mentioned at https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Is your workflow public - can you link to the output?

**Comment by devoncarew** [comment]
this was fixed by https://github.com/dart-lang/setup-dart/pull/122
