### ISSUE TITLE
Add a problem matcher for dart analyse

### ISSUE THREAD

**Issue by stof** [dart-lang/setup-dart#24]
Originally requested at https://github.com/cedx/setup-dart/issues/8

**Comment by serverwentdown** [comment]
```
{
  "problemMatcher": [
    {
      "owner": "flutter",
      "pattern": [
        {
          "regexp": "^\\s*(error|warning|info)\\s•\\s(.+)\\s•\\s(.+):(\\d+):(\\d+)\\s•\\s(.+)$",
          "file": 3,
          "line": 4,
          "column": 5,
          "severity": 1,
          "message": 2,
          "code": 6
        }
      ]
    }
  ]
}
```

**Comment by Albert221** [comment]
You can now use [leancodepl/dart-problem-matcher](https://github.com/leancodepl/dart-problem-matcher)

**Comment by ueman** [comment]
There's also https://github.com/invertase/github-action-dart-analyzer

**Comment by devoncarew** [comment]
Closing this as we're not planning to add this functionality directly to this action, but as noted above, there exists some solutions for people who do want this functionality:
- https://github.com/leancodepl/dart-problem-matcher
- https://github.com/invertase/github-action-dart-analyzer
