### ISSUE TITLE
Migrate v1 tag to point to v1.2

### ISSUE THREAD

**Issue by timsneath** [dart-lang/setup-dart#42]
As I understand it, the v1 (not v1.0) tag should always point to the Git ref of the current minor release, per https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management

This enables users to tag dart-lang/setup-dart@v1 and get the latest bug fixes. 

The idea is that users can both pin to a specific version (by tagging dart-lang/setup-dart@v1.0 in their workflow) or pin to a major version only. Right now, v1 still points to v1.0.

**Comment by timsneath** [comment]
Looks like this might not have worked, I'm afraid. Right now, the v1 tag still seems to point to the v1.0 hash.

```
$ git ls-remote --tags git@github.com:dart-lang/setup-dart.git | grep v1
57198e889390e8e71394826d8cb99056ec62bae3        refs/tags/v1
9a04e6d73cca37bd455e0608d7e5092f881fd603        refs/tags/v1^{}
63bf62f8d36031fe2755e5fd6356ded42fb99d73        refs/tags/v1.0
9a04e6d73cca37bd455e0608d7e5092f881fd603        refs/tags/v1.0^{}
fa07b23c84e2bdb044d78cb24e69cb6ba73a82ae        refs/tags/v1.1
ade92c2f32c026078e6297a030ec6b7933f71950        refs/tags/v1.2
6a218f2413a3e78e9087f638a238f6b40893203d        refs/tags/v1.3
```

**Comment by mit-mit** [comment]
Hmm, I'm a tags noob. Can you check again; I believe it's fixed now?

**Comment by timsneath** [comment]
Ah yes -- this looks right now. 

```
git ls-remote --tags git@github.com:dart-lang/setup-dart.git | grep v1
6a218f2413a3e78e9087f638a238f6b40893203d        refs/tags/v1
63bf62f8d36031fe2755e5fd6356ded42fb99d73        refs/tags/v1.0
9a04e6d73cca37bd455e0608d7e5092f881fd603        refs/tags/v1.0^{}
fa07b23c84e2bdb044d78cb24e69cb6ba73a82ae        refs/tags/v1.1
ade92c2f32c026078e6297a030ec6b7933f71950        refs/tags/v1.2
6a218f2413a3e78e9087f638a238f6b40893203d        refs/tags/v1.3
```

and I can see [the new version is being picked up](https://github.com/timsneath/advent-of-code-2021/runs/4397079540?check_suite_focus=true):
```
Installing Dart SDK version "latest" from the main channel (raw) on linux-x64
```
versus ([old, pre-flavors](https://github.com/timsneath/advent-of-code-2021/runs/4391220806?check_suite_focus=true))
```
Installing Dart SDK version "latest" from the main channel on linux-x64
```

Thanks!
