### ISSUE TITLE
Automatically choose the correct architecture

### ISSUE THREAD

**Issue by nex3** [dart-lang/setup-dart#59]
Currently, this action always defaults to installing the x64 Dart binaries, even when running on architectures that aren't compatible with x64 (such as MacOS ARM). It would be nice if it instead defaulted to checking the current architecture and installing the matching binary.

**Comment by nex3** [comment]
It looks like this is still an issue, at least for Mac OS ARM machines: https://github.com/sass/dart-sass/actions/runs/4388953095/jobs/7686128912

**Comment by devoncarew** [comment]
Are you using the published version of setup-dart or the latest from head?

**Comment by devoncarew** [comment]
We plan to publish ~next week (after a bit of burn-in time). https://github.com/dart-lang/setup-dart/issues/79 has info on how to use the version from head.

**Comment by nex3** [comment]
We're using the `@v1` tag. We'll probably wait to update until the stable version is published.
