### ISSUE TITLE
How to: automatic publishing with multiple packages

### ISSUE THREAD

**Issue by guidezpl** [dart-lang/setup-dart#67]
https://dart.dev/tools/pub/automated-publishing mentions "multiple packages" a couple of times. But it doesn't show how to specify `working-directory` to support this.

Is this possible or do I have to create a separate workflow for each package?

cc @devoncarew

**Comment by devoncarew** [comment]
There's an example of using automated publishing and mono-repos here:

    https://github.com/google/dart-neats/blob/master/.github/workflows/publish.yml

It's a creative combo of bash and sed.

Separately, the dart team has some prescriptive tooling built on top of the pub + github automation; https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose. That's not really intended for broad use but is something we ourselves will use to publish packages. It'll detect whether it's running from a single package repo or a mono-repo; you can see an example of the integration here: https://github.com/dart-lang/shelf/blob/master/.github/workflows/publish.yaml.

**Comment by guidezpl** [comment]
Oh nice! It would be worth pointing out in the docs that no further action is required

**Comment by jonasfj** [comment]
Dumped a comment in https://github.com/dart-lang/site-www/pull/4574

I think it's fairly reasonable to make a workflow file per package. The thing I did in dart-neats repo is only going to work in cases where the package folder is the package name, and the _tag pattern_ is `<package>-{{version}}`.

I'm open to providing better logic, but honestly, it's probably better if we just tweak `mono_repo` to generate workflows for publishing.

**Comment by jonasfj** [comment]
Filed https://github.com/google/mono_repo.dart/issues/434
