### ISSUE TITLE
Address breakages related to forthcoming changes to `dart:js_interop`

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/setup-dart#78]
The JS types in `dart:js_interop` are just typedefs today, but in the future they will be reified. As a result, we will have to explicitly insert calls to `toDart` / `toJS` to move data between Dart and JS.

This bug tracks the work to ensure `setup-dart` is fixed when `dart:js_interop` changes.

**Comment by mit-mit** [comment]
@joshualitt I updated this to use the new style interop recently. Is this issue then still relevant?

**Comment by joshualitt** [comment]
I have to take a closer look, but I think there might still be a bit more to do here. We will hopefully be reifying JS types on JS backends, and then we can see if there are any further updates needed.

**Comment by devoncarew** [comment]
I believe this issue has been addressed.
